
ARG REPO=
# ARG VER=22.04
FROM ${REPO}infrastlabs/x11-base:rootfs AS rootfs

# TOOD origin-hub's sync to ${REPO}
FROM registry.cn-shenzhen.aliyuncs.com/infrasync/v2025:library--ubuntu---22.04
ARG TARGETPLATFORM
ARG TYPE=app
# ARG VER=22.04
ENV \
  #env.bash for test "xx" == "yy"
  VER=22.04 \
  SHELL=/bin/bash \
  DEBIAN_FRONTEND=noninteractive \
  LOCALE_INCLUDE="zh_CN zh_HK zh_TW en en_AU fr fr_CA pt pt_BR es ar cs de it ru nl tr is sv uk ja ko th vi"
  # LOCALE_INCLUDE="en"
RUN echo "Acquire {\n\
  APT::Get::Allow-Unauthenticated \"true\";\n\
  GPG::Ignore \"true\";\n\
  AllowInsecureRepositories \"true\";\n\
  AllowDowngradeToInsecureRepositories \"true\";\n\
}" > /etc/apt/apt.conf.d/skip-gpg-check-ig;
RUN export DOMAIN="mirrors.ustc.edu.cn"; \
  case ${VER} in \
    "14.04")  V2=trusty  ;; \
    "16.04")  V2=xenial  ;; \
    "18.04")  V2=bionic  ;; \
    "20.04")  V2=focal   ;; \
    "22.04")  V2=jammy   ;; \
    "24.04")  V2=noble   ;; \
    "26.04")  V2=resolute ;; \
  esac; \
  sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list; \
  sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list; \
  sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources; \
  sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/ubuntu.sources; \
    \
  # default:echo -e;
  echo "path-exclude /usr/share/doc/*\n\
path-exclude /usr/share/man/*\n\
path-exclude /usr/share/locale/*\n\
path-exclude /usr/share/info/*\n\
path-exclude /usr/share/help/*\n\
path-exclude /usr/share/lintian/*\n\
" > /etc/dpkg/dpkg.cfg.d/excludes; \
  echo $LOCALE_INCLUDE |sed "s/ /\n/g" |while read one; do echo "path-include /usr/share/locale/$one/*" >> /etc/dpkg/dpkg.cfg.d/excludes; done; \
  cat /etc/dpkg/dpkg.cfg.d/excludes; \
  rm -rf /usr/share/locale/* ; \
  \
  # ubt14.04: err apt clean; E: Invalid operation clean
  echo 'apt update -qq && apt install -yq --no-install-recommends $@ && apt clean; rm -rf /var/lib/apt/lists/*; ' > /usr/local/bin/apt.sh \
    && chmod +x /usr/local/bin/apt.sh; \
  # for test "xx" == "yy"
  rm -f /bin/sh; ln -s /bin/bash /bin/sh;

# MISC 15.1 MB
RUN \
  apt.sh wget ca-certificates \
  curl \
  htop rsync tree tmux lrzsz psmisc fuse net-tools iputils-ping \
  procps sudo iproute2 iptables zip unzip xz-utils vim-tiny \
  openssh-sftp-server lftp jq \
  lame

  
# 25.9.13: +tzdata locales librsvg2-common
RUN apt.sh \
  tzdata \
  locales \
  # [librsvg2-common 11.8Kb>60.4Kb]>> 免icons配置不生效<flux/openbox,xfce4>
  librsvg2-common \
  x11-xserver-utils ; \
  \
  # for dbg
  apt.sh thunar; \
  test "24.04" != "${VER}" && apt.sh leafpad; \
  exit 0


##APP################################################
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\  
  # libllvm12 已包含 # libgl1-mesa-glx >libgl1-mesa-dri ##ex:  mesa-utils 
  apt.sh libglu1-mesa; \
  test "26.04" != "${VER}" && apt.sh libgl1-mesa-glx; \
  \
  # LLVM(定制版这里删调它,除gnome,cinna其它de无影响); clear big lib: 88M (qt: flameshot,sogoupinyin) > img: -27M
  rm -f /usr/lib/x86_64-linux-gnu/libLLVM-12.so.1; \
  rm -f /usr/lib/aarch64-linux-gnu/libLLVM-12.so.1; 

  # ubt icon-theme clear;
  RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
    apt.sh \
    hicolor-icon-theme adwaita-icon-theme humanity-icon-theme; \
    # cd /usr/share/icons && rm -rf Humanity* ubuntu-mono* LoginIcons Tango; \
    exit 0

# ubt2404-drop: libasound2 
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  mkdir -p /usr/share/X11/xkb; \
  apt.sh \
# gnome-sys-mon
  libgles2 \
# firefox #esr/115.1>> libdbus-glib-1-2
  libxtst6 libdbus-glib-1-2 \
# 163music v1.2.1
  libharfbuzz0b libpangocairo-1.0-0 libgdk-pixbuf2.0-0 \
# wps2019 11.1.0.11719
  libfreetype6 libcups2 libglib2.0-0 libglu1-mesa libsm6 libxrender1 libfontconfig1 libxext6 libxcb1 \
# vscode 1.88.1 ##libgtk-3-0: 16M; img: 362MB> 398MB > 475MB
  libnss3 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libgbm1; \
  exit 0

# LOC 87.4 MB # img: 362MB> 398MB > 433MB
# strip: binutils # xrdp-chansrv: libfdk-aac1 libopus0
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  # LOCALE 15.0 MB 
  apt.sh tzdata locales binutils dconf-cli \
  dbus-x11 at-spi2-core gtk2-engines-pixbuf \
  # 343 kB
  apt-utils x11-xkb-utils xdg-utils; \
  exit 0

  # AUD img: 546MB[239M]> 560MB # INPUT img: 546MB[239M]> 658MB[252M]
  RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
    apt.sh \
    # Audio 39.8 MB 
    pavucontrol \
    \
    # \12.3 MB (默认不含输入法: IBus/Fcitx)
    ibus ibus-gtk ibus-gtk3 ibus-rime librime-data-wubi; \
    exit 0

  # XFCE4
    # tint2 # plank rofi clipit pnmixer lxappearance thunar \
  RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
    apt.sh \
    # 2536 kB #18.9 MB > 14.3 MB
    xfwm4 xfdesktop4 \
    xfce4-notifyd xfce4-settings xfce4-session; \
    exit 0


    

  # MISC2 arandr
  # flameshot: none@1604,1404 
  RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
    test "14.04" == "${VER}" && exit 0; \
    test "16.04" == "${VER}" && exit 0; \
    apt.sh \
    # # \20.5 MB
    flameshot; \
    strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5; \
    strip --remove-section=.note.ABI-tag /usr/lib/aarch64-linux-gnu/libQt5Core.so.5; \
    exit 0
  # 预装软件: sakura geany ristretto sys-monitor engrampa asbru
  RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
    apt.sh thunar dunst clipit pasystray \
    pcmanfm lxappearance \
    sakura geany ristretto gnome-system-monitor; \
    # misc2
    \
    # link: sakura, thunar
    mv /usr/bin/st /usr/bin/st00; ln -s /usr/bin/sakura /usr/bin/st; \
    test "14.04" == "${VER}" && exit 0; \
    apt.sh plank engrampa; \
    exit 0


# firefox: ubt2204+>> @snap: snap install firefox
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  match1=$(echo "${VER}" |grep -E "22.04$|24.04$"); \
  test -z "$match1" && apt.sh firefox; \
  exit 0


# OHMYBASH # git ohmybash # \12.6 MB
RUN \
  echo a.123; \
  apt.sh x11-xserver-utils scrot ; \
  \
  test "app" != "$TYPE" && exit 0 || echo appInstall;\
  apt.sh git mousepad; \
  test "24.04" != "${VER}" && apt.sh leafpad; \
  \
  exit 0



# FONT, THEME, ICON
# font-ttf: @win:msyh.zip> fonts-wqy-microhei
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  apt.sh \
  greybird-gtk-theme \
  fonts-wqy-microhei language-pack-gnome-zh-hans; \
  \
  rm -f /usr/share/backgrounds/greybird.svg;

# split papirus-icon-theme: none@1604,1404
# bunsen-papirus-icon-theme> papirus-icon-theme; ERR: 14.04 16.04 1804?
RUN test "app" != "$TYPE" && exit 0 || echo appInstall;\
  test "14.04" == "${VER}" && exit 0; \
  test "16.04" == "${VER}" && exit 0; \
  test "18.04" == "${VER}" && exit 0; \
  echo a.123; \
  apt.sh \
  papirus-icon-theme; 
  # \
  # # 清理ubt自带图标, keep项: hicolor 
  # # locolor gnome bloom
  # cd /usr/share/icons && rm -rf Humanity* ubuntu-mono* LoginIcons Tango; \
  # \
  # wget https://gitee.com/infrastlabs/docker-headless/raw/dev/_doc/assets/bunsen-papirus-icon-theme_10.3-2_all.deb; \
  # dpkg -i bunsen-papirus-icon-theme_10.3-2_all.deb; rm -f bunsen-papirus-icon-theme_10.3-2_all.deb; \
  # cd /usr/share/icons && rm -rf Papirus-Bunsen-Dark-bluegrey Papirus-Bunsen-Dark-grey Papirus-Dark Papirus-Light ePapirus; \
  # \
  # # Papirus left: 16x(clipit:21M) 64x(desktop:21M)
  # cd /usr/share/icons/Papirus && rm -rf 18x* 22x* 24x* 32x*  48x* 64x* ; \
  # ls -lh /usr/share/icons/Papirus; \
  # \
  # dpkg -l |grep bunsen && exit 0 || exit 1;


# 拆分包体与配置项两块，免频繁变动基础包
# HEADLESS
# COPY --from=rootfs /rootfs/res_ubt_share /
COPY --from=rootfs /rootfs/files1 /
COPY --from=rootfs /rootfs/files2 /
RUN \
  # /xconf.sh app; inner TYPE judge
  bash /xconf.sh core; bash /xconf.sh app; \
  # ubt24: apt-dropbear; after:files1 ; #test: 24.04: unexpected operator
  test "24.04" == "${VER}" && apt.sh dropbear; \
  exit 0;

# EXPOSE 10089/tcp 10081/tcp 10022/tcp
CMD ["bash", "-c", "exec /entry.sh"]
ENV \
  TERM=xterm \
  SHELL=/bin/bash
  # 默认约定
  # L="zh_CN" \
  # TZ="Asia/Shanghai"


# ARG TARGETARCH
# ARG VER=app-ubuntu-20.04
# FROM registry.cn-shenzhen.aliyuncs.com/infrastlabs/x11-base:${VER}
RUN \
  echo a.1234; \
  # avoid: apt ins pulseaudio's replaceConfirm
  rm -f /etc/pulse/default.pa; \
  apt.sh \
  xserver-xorg pulseaudio \
  xserver-xorg-input-evdev \
  lame sox libsox-fmt-mp3 

# lame sox libsox-fmt-mp3
RUN \
  # chvt@kbd
  apt.sh beep dbus-x11 \
  kbd \
  # 260519:add
  less bash-completion tumbler \
  mesa-utils \
  xserver-xorg-video-intel \
  \
  # for: weipai-s11's touchpad; evtest /dev/input/event7 操作touch板即有反应
  xinput evtest \
  xserver-xorg-input-libinput xserver-xorg-input-synaptics \
  network-manager xfce4-power-manager \
  # alsa-oss alsa-tools-gui alsamixergui \
  alsa-tools alsa-utils mpg123 ; \
  echo "curl mp3.." && su - headless -c "curl --connect-timeout 3 -k -O -fSL https://downsc.chinaz.net/files/download/sound1/201309/3476.mp3";

RUN \
  apt.sh \
  pm-utils upower \
  rofi  xterm; \
  \
  #ubt1804.none: alsa-ucm-conf jgmenu
  apt.sh alsa-ucm-conf jgmenu; \
  # apt.sh network-manager-gnome; \
  exit 0

RUN \
    cd /usr/local/static/.dotfiles/; \
    git config --global --add safe.directory /usr/local/static/.dotfiles; \
    git fetch; git reset --hard origin/master; \
    bash refresh.sh; \
    exit 0

